/* Licensed under the MIT license:
 * http://www.opensource.org/licenses/mit-license.php
 * Copyright (c) 2010 Mr.doob, rhyolight, bebraw
 */
PREV_COLOR = 't'
NEXT_COLOR = 'y'

INCREASE_BRUSH_SIZE = 'w'
DECREASE_BRUSH_SIZE = 'q'

INCREASE_BRUSH_SIZE_JITTER = 'r'
DECREASE_BRUSH_SIZE_JITTER = 'e'

INCREASE_BRUSH_OPACITY = 's'
DECREASE_BRUSH_OPACITY = 'a'

INCREASE_BRUSH_OPACITY_JITTER = 'f'
DECREASE_BRUSH_OPACITY_JITTER = 'd'

INCREASE_BRUSH_LOCATION_JITTER = 'v'
DECREASE_BRUSH_LOCATION_JITTER = 'c'
