/* Licensed under the MIT license:
 * http://www.opensource.org/licenses/mit-license.php
 * Copyright (c) 2010 Mr.doob, rhyolight, bebraw
 */
PREV_COLOR = 'o'
NEXT_COLOR = 'p'

TOGGLE_BRUSH_SIZE_PRESSURE = 'q'
DECREASE_BRUSH_SIZE = 'w'
INCREASE_BRUSH_SIZE = 'e'
DECREASE_BRUSH_SIZE_JITTER = 'r'
INCREASE_BRUSH_SIZE_JITTER = 't'

TOGGLE_BRUSH_OPACITY_PRESSURE = 'a'
DECREASE_BRUSH_OPACITY = 's'
INCREASE_BRUSH_OPACITY = 'd'
DECREASE_BRUSH_OPACITY_JITTER = 'f'
INCREASE_BRUSH_OPACITY_JITTER = 'g'

DECREASE_BRUSH_LOCATION_JITTER = 'v'
INCREASE_BRUSH_LOCATION_JITTER = 'b'
